spring:
  application:
    name: AAP-prototype
  datasource:
    # DB 연결 정보 (포트 번호와 DB 이름 확인 필수)
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      # 테이블이 없으면 자동 생성, 있으면 변경된 부분만 업데이트
      ddl-auto: update
    show-sql: true # 실행되는 SQL을 콘솔에 출력
    properties:
      hibernate:
        format_sql: true # SQL을 보기 좋게 정렬
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: warn
    com.project.AAP_prototype: info  # 우리 프로젝트 로그만 깔끔하게 출력
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n" # 로그 포맷 단순화